[package]
name = "regex_generate"
version = "0.1.0"
authors = ["CryptArchy <codexarcanum@gmail.com>"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/CryptArchy/regex_generate"
documentation = "https://docs.rs/regex_generate"
homepage = "https://github.com/CryptArchy/regex_generate"
description = """
Use regular expressions to generate text.
"""
keywords = ["regex", "text", "generation"]
categories = ["text-processing"]

[dependencies]
rand = "0.3.15"
regex-syntax = "0.4.1"
byteorder = "1.0.0"

[dev-dependencies]
regex = "0.2.2"
